security:

    access_denied_url:    /access

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
                    user:
                        password: user
                        roles: 'ROLE_USER'

        our_db_provider:
            entity: { class: BlogBundle:User }

    encoders:
        BlogBundle\Entity\User:
            id: blog.user.pass.encoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                invalidate_session: true
                path: /logout
                target: /
            anonymous: true
            security: true
            switch_user: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }