test_blog_app:
    container_name: test_blog_app
    image: busybox
    volumes:
        - ../app:/var/www/app/

test_blog_nginx:
    container_name: test_blog_nginx
    build: builds/nginx
    volumes_from:
        - test_blog_app
    links:
        - test_blog_php:php
    volumes:
        - ./logs/nginx:/var/log/nginx

test_blog_php:
    container_name: test_blog_php
    build: builds/php-fpm
    volumes_from:
        - test_blog_app
    links:
        - test_blog_mysql:mysql
    working_dir: /var/www/app

test_blog_mysql:
    container_name: test_blog_mysql
    image: mysql:5.6
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db
        MYSQL_USER: root
        MYSQL_PASSWORD: root
